parameters:
    ngsite.default.search.content_types:
        - ng_blog_post
        - ng_article
        - ng_news
        - ng_category
        - ng_contact_form
        - ng_landing_page
        - ng_video
        - ng_audio
        - file

    ngsite.default.lazy_loading.enabled: true

    # Empty string for API key will mean that MailerLite newsletter integration is disabled
    ngsite.default.info_collection.mailer_lite.api_key: ''
